import type { LucideIcon } from 'lucide-react'
import type { DataTableDefinition } from '@/components/common/DataTable.types'
import {
  ArrowLeftRight,
  Boxes,
  Building2,
  ContactRound,
  CreditCard,
  FileBarChart,
  Forklift,
  HardHat,
  Package,
  Receipt,
  Shield,
  ShoppingCart,
  Truck,
  UserRoundCog,
  WalletCards,
} from 'lucide-react'

export type { RecordRow as Row } from '@/contracts/records'

export type ModuleDefinition = DataTableDefinition & {
  label: string
  description: string
  icon: LucideIcon
  group: string
  permission: string
  addLabel: string
}

export const modules: ModuleDefinition[] = [
  {
    id: 'users',
    label: 'Users & roles',
    title: 'Users & Roles',
    description: 'Manage accounts, access, and role assignments.',
    icon: UserRoundCog,
    group: 'Management',
    permission: 'users.read',
    addLabel: 'Add user',
    columns: ['Name', 'Email', 'Role', 'Branch', 'Status'],
    mobileColumns: ['Email', 'Role', 'Branch'],
  },
  {
    id: 'branches',
    label: 'Branches',
    title: 'Branches',
    description: 'View and manage branch locations.',
    icon: Building2,
    group: 'Management',
    permission: 'branches.read',
    addLabel: 'Add branch',
    columns: ['Branch', 'Code', 'Manager', 'Phone', 'Status'],
    mobileColumns: ['Code', 'Manager', 'Phone'],
  },
  {
    id: 'employees',
    label: 'Employees',
    title: 'Employees',
    description: 'Employee records, positions, and branch assignments.',
    icon: HardHat,
    group: 'People',
    permission: 'employees.read',
    addLabel: 'Add employee',
    columns: ['Name', 'Employee ID', 'Position', 'Branch', 'Phone', 'Hire date', 'Status'],
    mobileColumns: ['Employee ID', 'Position', 'Branch', 'Phone', 'Hire date'],
  },
  {
    id: 'customers',
    label: 'Customers',
    title: 'Customers',
    description: 'Customer directory and account details.',
    icon: ContactRound,
    group: 'People',
    permission: 'customers.read',
    addLabel: 'Add customer',
    columns: ['Customer', 'Contact', 'Phone', 'Location', 'Branch', 'Status'],
    mobileColumns: ['Contact', 'Phone', 'Location', 'Branch'],
  },
  {
    id: 'suppliers',
    label: 'Suppliers',
    title: 'Suppliers',
    description: 'Supplier contacts, categories, and payment terms.',
    icon: Forklift,
    group: 'People',
    permission: 'suppliers.read',
    addLabel: 'Add supplier',
    columns: ['Supplier', 'Contact', 'Phone', 'Category', 'Payment terms', 'Status'],
    mobileColumns: ['Contact', 'Phone', 'Category', 'Payment terms'],
  },
  {
    id: 'products',
    label: 'Products',
    title: 'Products',
    description: 'Product catalog, pricing, and availability.',
    icon: Package,
    group: 'Operations',
    permission: 'products.read',
    addLabel: 'Add product',
    columns: ['Product', 'SKU', 'Category', 'Unit', 'Unit price', 'Status'],
    mobileColumns: ['SKU', 'Category', 'Unit', 'Unit price'],
  },
  {
    id: 'inventory',
    label: 'Inventory',
    title: 'Inventory',
    description: 'Track branch stock and manage stock movements.',
    icon: Boxes,
    group: 'Operations',
    permission: 'inventory.read',
    addLabel: 'Adjust stock',
    columns: [
      'Product',
      'SKU',
      'Branch',
      'On hand',
      'Reserved',
      'Available',
      'Reorder point',
      'Status',
    ],
    mobileColumns: ['Branch', 'On hand', 'Reserved', 'Available', 'Reorder point'],
  },
  {
    id: 'transfers',
    label: 'Stock transfers',
    title: 'Stock Transfers',
    description: 'Review inventory moving between branches.',
    icon: ArrowLeftRight,
    group: 'Operations',
    permission: 'inventory.transfer',
    addLabel: 'New transfer',
    columns: ['Transfer ID', 'From', 'To', 'Items', 'Requested', 'Status'],
    mobileColumns: ['From', 'To', 'Items', 'Requested'],
  },
  {
    id: 'orders',
    label: 'Orders',
    title: 'Orders',
    description: 'Track customer orders from placement to fulfillment.',
    icon: ShoppingCart,
    group: 'Operations',
    permission: 'sales.read',
    addLabel: 'Create order',
    columns: ['Order', 'Customer', 'Date', 'Amount', 'Branch', 'Status'],
    mobileColumns: ['Customer', 'Amount', 'Branch', 'Date'],
  },
  {
    id: 'payments',
    label: 'Payments',
    title: 'Payments',
    description: 'Review customer transactions, payment history, and remaining balances.',
    icon: CreditCard,
    group: 'Finance',
    permission: 'payments.read',
    addLabel: 'Record payment',
    columns: [
      'Order',
      'Customer',
      'Total Amount',
      'Amount Paid',
      'Remaining Balance',
      'Status',
      'Last Payment Date',
    ],
    mobileColumns: ['Customer', 'Remaining Balance', 'Amount Paid', 'Total Amount'],
  },
  {
    id: 'deliveries',
    label: 'Deliveries',
    title: 'Deliveries',
    description: 'Coordinate delivery schedules, drivers, and proof of delivery.',
    icon: Truck,
    group: 'Operations',
    permission: 'deliveries.read',
    addLabel: 'Schedule delivery',
    columns: ['Delivery', 'Order', 'Destination', 'Driver', 'Schedule', 'Status'],
    mobileColumns: ['Order', 'Destination', 'Driver', 'Schedule'],
  },
  {
    id: 'vehicles',
    label: 'Vehicles',
    title: 'Vehicles',
    description: 'Manage fleet availability, assignments, and maintenance.',
    icon: Truck,
    group: 'Operations',
    permission: 'vehicles.read',
    addLabel: 'Add vehicle',
    columns: ['Vehicle', 'Plate number', 'Type', 'Capacity', 'Default driver', 'Branch', 'Status'],
    mobileColumns: ['Branch', 'Plate number', 'Capacity'],
  },
  {
    id: 'driver-allowances',
    label: 'Driver allowances',
    title: 'Driver Allowances',
    description: 'Historical driver allowances and remaining receipt confirmations.',
    icon: WalletCards,
    group: 'Finance',
    permission: 'driver-allowances.read',
    addLabel: '',
    columns: ['Transaction', 'Driver', 'Type', 'Amount', 'Status', 'Date'],
    mobileColumns: ['Driver', 'Amount', 'Type'],
  },
  {
    id: 'expenses',
    label: 'Expenses',
    title: 'Expenses',
    description: 'Review and track branch operating expenses.',
    icon: Receipt,
    group: 'Finance',
    permission: 'expenses.read',
    addLabel: 'New expense',
    columns: ['Expense', 'Category', 'Branch', 'Submitted by', 'Date', 'Amount', 'Status'],
    mobileColumns: ['Amount', 'Branch', 'Category', 'Submitted by', 'Date'],
  },
  {
    id: 'payroll',
    label: 'Payroll',
    title: 'Payroll',
    description: 'Review employee pay, allowances, payments, and receipt confirmation by period.',
    icon: WalletCards,
    group: 'Finance',
    permission: 'payroll.read',
    addLabel: 'Create pay run',
    columns: ['Pay run', 'Period', 'Employees', 'Gross pay', 'Net pay', 'Paid', 'Branch', 'Status'],
    mobileColumns: ['Period', 'Employees', 'Net pay', 'Paid', 'Branch'],
  },
  {
    id: 'reports',
    label: 'Reports',
    title: 'Reports',
    description: 'Explore sales, inventory, finance, and operations reports.',
    icon: FileBarChart,
    group: 'Insights',
    permission: 'reports.view',
    addLabel: 'Create report',
    columns: ['Report', 'Category', 'Period', 'Last generated', 'Owner', 'Status'],
  },
  {
    id: 'audit-logs',
    label: 'Audit logs',
    title: 'Audit Logs',
    description: 'Review important changes across the workspace.',
    icon: Shield,
    group: 'Insights',
    permission: 'audit.read',
    addLabel: 'Export logs',
    columns: ['Action', 'User', 'Module', 'Branch', 'Date & time'],
    mobileColumns: ['User', 'Module', 'Branch', 'Date & time'],
  },
]

export const navGroups = ['Management', 'People', 'Operations', 'Finance', 'Insights']
